### ISSUE TITLE
Mantine refactor follow-up

### ISSUE THREAD

**Issue by DJDavid98** [DJDavid98/HammerTime#103]
Some issues remain open after merging #81, they should be addressed separately:
- [x] https://github.com/mantinedev/mantine/discussions/1759
- [x] https://github.com/mantinedev/mantine/discussions/1966
- [x] https://github.com/mantinedev/mantine/discussions/2105

**Comment by LoryPelli** [comment]
For the third task take a look at this https://rtivital.github.io/mantine-dates-6/

**Comment by DJDavid98** [comment]
Done in 2c91f9baf3f08fab7181522346d3471c036f570d
