### ISSUE TITLE
Useability improvements

### ISSUE THREAD

**Issue by RedEagleP1** [DJDavid98/HammerTime#104]
I love what you have done with Hammertime. 

I use it so often that I get people's first reaction to the website on a daily basis. 

I think usability could be improved by moving this option up and closing the other options to a click-to-open menu just to give them less choice and more clarity. 
[https://i.imgur.com/DzmqQq4.png](https://i.imgur.com/DzmqQq4.png)

**Comment by DJDavid98** [comment]
Sorry but I intend to keep all options visible at all times, I don't want to hide other syntax options behind another click
