### ISSUE TITLE
Wrong folder name of the Brazilian Portuguese translation?

### ISSUE THREAD

**Issue by ShadowG11** [DJDavid98/HammerTime#109]
I made some of the translations to Brazilian Portuguese on Crowdin some days ago and I just came here to check the repo.
But I saw the commits (3eb34bfcaa38ca8382b8fdf40f4614688588d220 and a6b8ad35fc19cf414e6e4e57472c52c393529637) and I believe they're in the wrong folders, should be "pt-BR" instead of "pr-BR".

And thanks for making this website, it helped me a lot :)
(sorry if this was posted in the wrong section, it's my first issue)

**Comment by DJDavid98** [comment]
Thank you for letting me know, this should now be fixed.
