### ISSUE TITLE
HammerTime shows "in x days" while Discord shows "Month DD, YYYY" if the date is seven days or more away

### ISSUE THREAD

**Issue by Gestrid** [DJDavid98/HammerTime#114]
For reference, it is currently September 13, 2022.
1. Choose a date and time on https://hammertime.cyou/ that's seven days or more away.
2. Copy the <t:XXXX:R> timestamp to Discord.
3. The timestamp on the HammerTime website will say, for example, "in 7 days", but, when pasted into Discord, it says "Sep 20, 2022". The website is inconsistent with how Discord displays timestamps.

**Comment by ZaptorZap** [comment]
Hmmmm? I can't reproduce this on the 13th of January, 2023.
![image](https://user-images.githubusercontent.com/64891705/212430902-18e80cf1-583e-45d0-bd85-749e4026c3ed.png)

**Comment by Gestrid** [comment]
It's possible there's been an update to Discord since I posted this back in September. I'll test it.

**Comment by Gestrid** [comment]
I've now retested this in Discord's WIndows version. Looks like Discord has since fixed the issue so it displays `in 7 days` now instead of the date of the timestamp.
