### ISSUE TITLE
Time zones seem to be backwards

### ISSUE THREAD

**Issue by Tamijo-Netrunner** [DJDavid98/HammerTime#12]
I am currently in GMT +1. It shows my time correctly when I select GMT -1.

When we were attempting to use this feature to send times to each other it seems to reverse the GMT +/- for everybody viewing it.

**Comment by Tamijo-Netrunner** [comment]
Examples of the issue:

Using the relative time (x minutes ago) we can see where the issue is.

![image](https://user-images.githubusercontent.com/39098450/133604869-858488de-6107-4643-9115-fdfbe36b29d9.png)

I have input my own time zone and time, and it is giving me odd results. 

![image](https://user-images.githubusercontent.com/39098450/133605077-152d3f31-bdbd-4c48-8a26-f323d4967ed9.png)

In this second screenshot you can see it now shows my time.

**Comment by DJDavid98** [comment]
D'oh! I did some light research and found the identifiers are intentionally inverted in those names:
* https://stackoverflow.com/a/39781455
* https://gitter.im/moment/moment-timezone?at=5630ed7fe16589782d931772

I'll push an update shortly to map these to the proper labels.

**Comment by DJDavid98** [comment]
Thank you for raising this issue, the fix is now live. As an added bonus, I sorted all GMT time zones to the start of the list to make them easily selectable by simply scrolling.
