### ISSUE TITLE
Hour picker gets stuck on DST shifting an hour forward

### ISSUE THREAD

**Issue by Nixitur** [DJDavid98/HammerTime#14]
Steps to reproduce:
1. Change timezone to "Europe/Berlin"
2. Enter time as "March 27, 2022 1:30:00 AM", timestamp 1648341000
3. Press the "Up" button on the hour picker

Expected behavior:
Time changes to "March 27, 2022 3:30:00 AM", timestamp 1648344600

Current behavior:
Time very briefly changes to "March 27, 2022 2:30:00 AM" (a non-existent time in Europe/Berlin), then automatically goes back to "March 27, 2022 1:30:00 AM"

The same behavior can be observed by instead going to "March 27, 2022 3:30:00 AM", timestamp 1648344600 first, then trying to go an hour back. It will again try to go to the fake time of "March 27, 2022 2:30:00 AM" before deciding to just stay at 3:30 AM instead.

**Comment by DJDavid98** [comment]
Thank you for reporting the issue, this is the date picker working to prevent an invalid date from being entered. As it is a 3rd-party component I'm just using in this project this might not be a simple fix. I would suggest that you try holding down the hour button to step more than 1 hour at a time, this way you can enter the desired date.

I agree that this is not great UX, but this is the best I can suggest for now. I'm leaving the issue open in case I manage to find a simple fix or a better date picker component that handles this more gracefully.

**Comment by DJDavid98** [comment]
This will have been solved by the changes made to address #8, it's now up to the browser to provide a working time picker, so I'm closing this issue.
