### ISSUE TITLE
Feature request: set timezone via URL

### ISSUE THREAD

**Issue by PrincessRTFM** [DJDavid98/HammerTime#144]
In a similar vein to #23, I would like to be able to set the timezone via URL when loading the page. Specifically, this would be useful when talking with friends who didn't use the tool, such that they can say "at 3pm" and I can simply load a bookmarked HammerTime page with their timezone and punch in the time to get a timestamp for it, without having to first convert between their timezone and mine - which nearly defeats the purpose of the tool - or having to remember exactly what timezone they're in.

**Comment by DJDavid98** [comment]
Thank you for the suggestion, after manually selecting a time zone it will now be added to the URL and persist across page loads.
