### ISSUE TITLE
Hide sidebar on pc also

### ISSUE THREAD

**Issue by lorypelli** [DJDavid98/HammerTime#145]
The layout with the sidebar doesn't feel good for me...even if I request to put it on the left (I like it more btw), I still don't like it, so it would be nice to have a button to hide it like it's on mobile

**Comment by lorypelli** [comment]
it will be default showed and you can hide it with a button (will be remembered in localstorage)

**Comment by DJDavid98** [comment]
Toggle button is now also available on desktop
