### ISSUE TITLE
Low performances

### ISSUE THREAD

**Issue by lorypelli** [DJDavid98/HammerTime#155]
This repo doesn't have good performances as I saw on page insight so why don't you make something server-side instead of client-side if you can?

**Comment by DJDavid98** [comment]
It does not make sense to calculate time on the server side, it's more costly and some functionality simply requires JavaScript. Could the site be faster? Absolutely. Do I have the time and interest to rebuild it from the ground up with the only goal in mind being performance? Sadly, no.

**Comment by timelessnesses** [comment]
> This repo doesn't have good performances as I saw on page insight so why don't you make something server-side instead of client-side if you can?

It is decent performance even on mobile devices, plus it seems very unnecessary to calculate the time on server-side.

**Comment by lorypelli** [comment]
> > This repo doesn't have good performances as I saw on page insight so why don't you make something server-side instead of client-side if you can?
> 
> It is decent performance even on mobile devices, plus it seems very unnecessary to calculate the time on server-side.

I used pagespeed insight
