### ISSUE TITLE
Does not work with interesting edgecases

### ISSUE THREAD

**Issue by HuskyNator** [DJDavid98/HammerTime#166]
It turns out <t:1234:r> is not something discord can handle.
: 1234 : will be converted to 🔢 before it's interpreted as an epoch.
The same goes for 💯.
<t:01234:r> will work fine though. :)

For reference, that's the epochs:
januari 1st 1970 00:20:34 GMT 🔢 
januari 1st 1970 00:01:40 GMT 💯

**Comment by DJDavid98** [comment]
I appreciate you reporting this, however I do not plan to handle weird edge cases specially, this is a tool and if you choose to shoot yourself in the foot with it I won't be able to stop you.

**Comment by vegeta897** [comment]
I'd also say this is a Discord issue more than a HammerTime one. When it comes to creating straightforward tools, the simple and predictable approach is always better than the clever one that may become unnecessary later. The tool doing what you tell it to do is always better than the tool trying to predict and solve an issue.
