### ISSUE TITLE
The page is showing and incorrect date and time for America/Mexico_City timezone

### ISSUE THREAD

**Issue by Aguileitus** [DJDavid98/HammerTime#167]
![image](https://github.com/DJDavid98/HammerTime/assets/14335637/e0b3cbac-c89c-4aea-b10b-c0d1a5789e36)
As you can see in the image, Date and time is showing one hour ahead (the example result is fine). This is probably because two years ago DST was removed for that specific timezone.

https://www.timeanddate.com/time/zone/mexico/mexico-city

**Comment by mpeddicord** [comment]
I second this. This is because Mexico only recently stopped observing daylight savings.

**Comment by mpeddicord** [comment]
Right on, dude. Quick work.

**Comment by DJDavid98** [comment]
moment-timezone has been updated to the latest version, please check if the issue persists and reopen if so.
