### ISSUE TITLE
Unlocking the timestamp from a URL desyncs unix time

### ISSUE THREAD

**Issue by DrSakuu** [DJDavid98/HammerTime#169]
When you follow a locked link to the HammerTime page and then unlock the timestamp to edit it, the unix time desyncs because the timezone is changed from GMT to local time zone. When unlocking changes the time zone, it should also convert the input time fields so the unix time stays the same, because that is more important. Locking the timestamp also changes the time zone to GMT without converting the input fields, so the unix time get desynced in that case too.

![20240421_141956-kgEB-msedge](https://github.com/DJDavid98/HammerTime/assets/9019979/963ed933-8b4f-4d4c-9bcb-ac5f74bfde44)
![20240421_142016-dPoy-msedge](https://github.com/DJDavid98/HammerTime/assets/9019979/7ee58e63-740e-4f4d-8979-d77bdb6ff82b)

**Comment by DJDavid98** [comment]
"Unlocking" currently does not attempt to preserve the timestamp selection, this is by design due to the complexity/limitations of the current approach of rendering the site. I hope to improve on this as part of the [SledeGammerTime](https://sledgehammerti.me) rewrite of the project.
