### ISSUE TITLE
[Not an Issue] - Is it possible to update this tool to show a countdown like this

### ISSUE THREAD

**Issue by DaddyBoard** [DJDavid98/HammerTime#170]
Is it possible to update this tool to show a countdown like this

2 days, 9 hours, 4 minutes, 6 seconds

**Comment by Jessuhh** [comment]
Unfortunately you cannot. From the [HammerTime Discord FAQ](https://discord.com/channels/952258283882819595/995284060941336647/996673769743601694):

> ### 1) Can you change how the time and/or date is displayed by Discord?
> No, the display of the timestamp syntax is entirely left up to Discord ([documented here](https://discord.com/developers/docs/reference#message-formatting-timestamp-styles)), what HammerTime does is simply provide a convenient way for you to get the code needed to use these pre-existing built-in formats. In simple terms this means I cannot help you:
> - change how the timestamp looks in any way, shape, or form
> - make it display a specific format regardless of client language settings
> - add additional information, like a timezone
> - change what is in the tooltip or hide it entirely
> 
> If you would like additional formatting options, please [send a feature request to Discord](https://support.discord.com/hc/en-us/articles/213490807-Where-can-I-submit-Feature-Requests-Feedback-and-Suggestions-).

**Comment by DJDavid98** [comment]
Technically speaking, the website could show a countdown like this but it would have little practical use as you would not actually be able to put this in a Discord message. If you just need such a countdown website I suggest https://www.timeanddate.com/countdown/create

**Comment by DaddyBoard** [comment]
> Technically speaking, the website could show a countdown like this but it would have little practical use as you would not actually be able to put this in a Discord message. If you just need such a countdown website I suggest https://www.timeanddate.com/countdown/create
![image](https://github.com/DJDavid98/HammerTime/assets/48053193/bfbe4ccc-a3db-4e72-9cfb-b24514884fb7)

It's more-so for embedded messages like ^


![image](https://github.com/DJDavid98/HammerTime/assets/48053193/e534ef8b-6262-4eea-864f-d100d9638715)

And I also made a countdown feature on my discord bot which kept updating every 5 seconds manually with time calculation, which "worked" but was pretty heft and filled my audit log with constant changes, so I opted to use this HammerTime instead but its just not enough to work as a good countdown (still love HammerTime tho)
