### ISSUE TITLE
Support for military time and DD/MM/YYYY

### ISSUE THREAD

**Issue by ThePolyBlank** [DJDavid98/HammerTime#18]
It would be incredibly helpful for international users if there was a setting to enter dates and times in both military time and DD/MM/YYYY

**Comment by kav2k** [comment]
Seems somewhat weird that there is a locale selector on the site itself, yet the format does not obey it. That is confusing for the end-user.

Interestingly, the site language defaults to English UK to me, but the format still follows English US preference in accept-language.
