### ISSUE TITLE
Output without year?

### ISSUE THREAD

**Issue by gucciBane** [DJDavid98/HammerTime#29]
Hey,

Is it possible to add an option that outputs like
Tuesday, January 20, 10:00 pm.
(no year?)

Thanks so much for this tool!

**Comment by DJDavid98** [comment]
The output formats are defined by Discord (more accurately the Momeent.js library) and cannot be changed by the tool. If you'd like more formats to be available, you need to rase this as a feature request to Discord as they are the only one able to support additional formats.
