### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by wolfling366** [DJDavid98/HammerTime#30]
`This Deployment has been disabled.

Your connection is working correctly.

Vercel is working correctly.

402: PAYMENT_REQUIRED
Code: DEPLOYMENT_DISABLED
ID: syd1::zvv5j-1641460122118-9691eab7801e

If you are a visitor, contact the website owner or try again later.
If you are the owner, please read this documentation section.`

**Comment by DJDavid98** [comment]
The website has been restored, there was an issue with the hosting provider disabling my account due to "excessive usage" for no apparent reason. I contacted their support but I'll probably end up moving to a different host entirely.
