### ISSUE TITLE
Is the a flag for the timezone in which the timstamp is being viewed?

### ISSUE THREAD

**Issue by crantok** [DJDavid98/HammerTime#31]
When I see these timestamps used on servers, they almost always look something like "15 January 2022 19:00 (in your timezone)". That looks tedious to me. I wondered whether it would be possible to have a flag that includes the timezone in which the timsstamp is being viewed. This would be particularly cool for people who are travelling between timezones and are not 100% sure which timezone discord is currently using.

**Comment by DJDavid98** [comment]
The appearance of the timestamps syntax in messages is controlled solely by Discord, if you'd like it to display anything differently you'll have to send that feature request to their support channels.
