### ISSUE TITLE
Reconsider NFT Integration 

### ISSUE THREAD

**Issue by aw-0** [DJDavid98/HammerTime#32]
NFTs as a whole are a controversial but interesting concept. However, selling a publicly available _unix timestamp_ for $1,000+ makes absolutely no sense. (For a plethora of reasons, e.x: who owns time? how does "HammerTime" own a timestamp?)

![image](https://user-images.githubusercontent.com/43796708/150444572-4a781bf3-c516-4bf1-9528-20d7ad6366cf.png)

I understand that you, as the maintainer, should deserve some monetary compensation for creating a useful tool. However, selling an NFT of **time** does not make sense. If you're looking for compensation, it's probably best to list your crypto wallet on the site (as it seems you're into crypto), or use a service like [BuyMeACoffee](https://www.buymeacoffee.com/), [Patreon](https://www.patreon.com/) or even [Github Sponsors](https://github.com/sponsors). 

Appreciate your consideration.

**Comment by DJDavid98** [comment]
I would like to invite you to click either of the two buttons, or simply peek in the bottom right corner ^^

**Comment by DJDavid98** [comment]
This might also give you a hint what that button is wired to:
https://github.com/DJDavid98/HammerTime/blob/610a93ee5b8d65730b1f554d26b3bd66a93ecc1f/src/util/nft.ts#L40-L55

**Comment by aw-0** [comment]
🤦 let's just forget i opened this, sorry about that

**Comment by DJDavid98** [comment]
If anything I'm glad it's convincing enough to prompt such an issue, I intentionally made it easy to dismiss for those who don't care and also easy to click on for any aspiring crypto millionaires. For the record, as an artist myself, I despise anyone who supports NFTs primarily due to the rampant art theft it enables but also the non-negligible environmental impact. I appreciate you genuinely raising your concern, please don't let this discourage you from doing the right thing anywhere else :)

**Comment by lyze237** [comment]
Awesome project, awesome rickroll!

Do you think changing the "what is an nft" to the Dan Olsons video would be a good idea? https://www.youtube.com/watch?v=YQ_xWvX1n9g

**Comment by DJDavid98** [comment]
Considering that video is over 2 hours long, I don't think so. There's a lot of detail one can go into regarding the subject, but ultimately this is a small harmless joke and I really don't expect someone clicking on that link to watch such a long video in its entirety. I'd hope those actually interested in learning more about the topic will find other avenues to sate their curiosity than a silly timestamp generator website.

**Comment by vegeta897** [comment]
I just want to say bravo, well done.

**Comment by 4P5** [comment]
Here like all the others—I was going to complain and I actually felt pretty sad as I use the site quite a bit, then I clicked the "what is an NFT" link, then the purchase link, then it all clicked. Very well done!

**Comment by DJDavid98** [comment]
I just came across this BS advertisement in the wild; this is getting out of hand *sigh*

![Reddit advertisement for a company selling NFTs of colors](https://user-images.githubusercontent.com/81610442/152637190-a86a12a4-bc2a-4289-8654-800fc21082e4.jpg)

**Comment by SpencerDub** [comment]
I'm very happy that I checked out this issue, because I was similarly annoyed by the seeming ad, and missed some of the finer details.

**Comment by DJDavid98** [comment]
As far as I can tell there's already a few forks in various states from people who did not get it's a joke. Ultimately this is an open source project and anyone is free to fork it at any time for any reason, if someone is motivated to learn how to remove this code from the app and set up their own server to run it, that's still a net win in my book, those skills will be useful later :)

**Comment by csuhta** [comment]
I support your motivation to troll NFT/ETH users, but I don't think the joke is particularly well-executed here. I essentially had this happen:

1. Visit the page
2. See the fake ad, not know it was fake, it seems plausible enough
3. I dismissed the banner and did not click inside it, and became annoyed/disgusted with the tool until I saw this GitHub issue a few days later.

Savvy users are trained by the internet to not click inside any ads, especially ones we don't like. And there seems to be enough other confusion noted here.

More good could probably be served if this section of the site linked to anti-crypto resources, or provided warnings about common Discord scams, or just provided links to other projects you support instead.

**Comment by vegeta897** [comment]
Unfortunately I have to agree with @csuhta. I run the site https://snowsta.mp and I considered adding a link to HammerTime to direct my visitors to a useful related resource, but I know there are going to be people that assume I'm endorsing NFT/crypto as soon as they see that and investigate no further.

Obviously there are innumerable user assumptions that are outside of our control, but this feels like a case where the message could be sent in a more effective way.

**Comment by DJDavid98** [comment]
If the overarching consensus is that this is turning people away and you are not comfortable using the site as a resource as a result then I'm happy to get rid of it in favor of something better. I honestly feel like I underestimated the amount of people actually using this site, and with enough traffic there's bound to be enough people who will be turned off by it. For the immediate future I can get rid of the banner entirely and come up with an alternative later.

**Comment by DJDavid98** [comment]
The fake box has been completely removed from the codebase, that's where I'll leave this specific issue for now, thanks to everyone for raising your concerns!
