### ISSUE TITLE
Improvement: Add option to show only day & time.

### ISSUE THREAD

**Issue by Sportiax** [DJDavid98/HammerTime#39]
This has been incredibly useful, I have been updating each week with the full date Wednesday, February 16, 2022 9:00 PM, asking if there could be an option to only show the date and time such as Wednesday, 9:00 PM.

**Comment by DJDavid98** [comment]
The displayed date formats are handled entirely by Discord, the tool cannot generate formats that Discord itself does not support. Please request this feature through their support channels.
