### ISSUE TITLE
Feature request Month Abbreviation (TLA)

### ISSUE THREAD

**Issue by iNgeon** [DJDavid98/HammerTime#40]
To simplify text volume would it be possible to please add an option for three letter abbreviated month names

Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec

https://www.aresearchguide.com/monthdayabb.html

**Comment by DJDavid98** [comment]
The displayed date formats are handled entirely by Discord, the tool cannot generate formats that Discord itself does not support. Please request this feature through their support channels.
