### ISSUE TITLE
Idea: Use ISO 8601 

### ISSUE THREAD

**Issue by DriesMoo** [DJDavid98/HammerTime#42]
It might help to use this standard. Who doesn't love some good ISO?
[https://en.wikipedia.org/wiki/ISO_8601](url)

Keep up the awesome work!

**Comment by DJDavid98** [comment]
Date inputs are controlled by the browser locale, and the displayed output format is dictated by Discord. I love standard date and time formats myself, but I can't easily modify these components' behaviour.
