### ISSUE TITLE
Unnecessary empty list elements in time picker

### ISSUE THREAD

**Issue by ladybunne** [DJDavid98/HammerTime#52]
Hi again! Upon playing with the time picker, I noticed there's some odd gaps between some elements. I've posted a screenshot below.

This doesn't really affect my use of the website since I'd probably just manually enter times, but I thought it might be worth reporting.

![image](https://user-images.githubusercontent.com/4102334/159600325-bcbcb365-65d4-426e-92b5-e9efc0a1ee65.png)

**Comment by ladybunne** [comment]
Also it looks like manual text input is disabled now, because of the changes to the pickers.

**Comment by LeigerGaming** [comment]
> Also it looks like manual text input is disabled now, because of the changes to the pickers.

Yeah I can't manually input the time any more with my keyboard. Came here to check if there was a recent update that broke this as the date picker looked new as well.

Sounds like you're aware of it, at least :)

**Comment by DJDavid98** [comment]
I have updated the inputs to only trigger the picker when the calendar or time icons are clicked, this should allow typing into the input field like before. Please take a look if the issue is now resolved. The gaps are entirely in the browser's hands, I can't do much about that.

**Comment by LeigerGaming** [comment]
@DJDavid98 the manual typing of the time works great again. Thanks :)
