### ISSUE TITLE
Set to current time ignores timezone field change

### ISSUE THREAD

**Issue by supermarth64** [DJDavid98/HammerTime#58]
If you change the timezone to one that's different from your actual timezone and then click on the `Set to current time` button, it sets the `Date and time` field to your timezone's current time without accounting for the timezone difference. For example, if I'm on Eastern time and I set the timezone to Pacific, clicking current time ends up setting it to my time+3 hours.

**Comment by DJDavid98** [comment]
This is a fair point, until it's resolved I suggest first setting the time before changing the timezone, then it should convert correctly

**Comment by DJDavid98** [comment]
Thank you for the report, a proper solution was implemented that should resolve the issue, please check again and reopen the issue if the problem persists.
