### ISSUE TITLE
Firefox: some labels don't disappear after mouseout

### ISSUE THREAD

**Issue by barbeque-squared** [DJDavid98/HammerTime#59]
How to reproduce:
- **Use Firefox** (on Chromium this works fine?)
- Mouseover the "Rewind clock" and/or "Lock/Unlock" icon and mouseout again

Expected behaviour: label disappears on mouseout

Actual behaviour: label remains. it gets appended to the `<body>` but never removed.

Additional notes: strangely, mousein/mouseout on the "Copy to clipboard" buttons also has labels and those work just fine.
I use Firefox 99.0 on Archlinux, if that even matters here.

![2022-04-08-165552_798x268_scrot](https://user-images.githubusercontent.com/5775429/162468356-81811478-9ef9-462e-88c0-14271b284b96.png)

**Comment by DJDavid98** [comment]
Thank you for the report, the root cause was identified and a fix was implemented, please reopen if the issue persists.
