### ISSUE TITLE
Typing in a time.

### ISSUE THREAD

**Issue by Quailsnap** [DJDavid98/HammerTime#8]
Currently times must be manually selected by hour, minute, and second with an up and down arrow. Minute and second can, worst-case, require 30ish clicks to get where you want. Shift/ctrl+clicking for groups of 10 would help, but what would be best is allowing people to simply type in the time.

**Comment by DJDavid98** [comment]
I understand the frustration, but I don't have time to implement my own date picker, and this one I'm using now was the best one I could find. I suggest holding down the spinner button to adjust it quicker rather than clicking it multiple times.

**Comment by a-hodges** [comment]
Most browsers implement a native time picker as <input type="time"> which would work much better, especially on mobile. The only exception would be internet explorer.

**Comment by DJDavid98** [comment]
That's a good point, I could actually just split the current 2 into 3 inputs, date, time, and timezone. Date and time input both exist separately in most clients, so that will probably be fine. I'll keep you posted on new developments here.
