### ISSUE TITLE
Incorrect flag for arabic

### ISSUE THREAD

**Issue by ZebaSz** [DJDavid98/HammerTime#9]
The flag for Arabic in the language selector is actually the flag of Argentina (`AR` 🇦🇷), which speaks Spanish

![image](https://user-images.githubusercontent.com/526469/132587693-af299f4a-173a-4d2d-b549-b785546fa615.png)

More appropriate flags might be those of Saudi Arabia (`SA` 🇸🇦) or United Arab Emirates (`AE` 🇦🇪 )

**Comment by DJDavid98** [comment]
Sorry about that, I completely missed it. I checked and AE was available in the flag icon library so I've replaced it with that one, it should be live in a few minutes.

**Comment by ZebaSz** [comment]
Holy smokes that was fast. Thanks a lot! 😄
